
# AccessToken : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjBmM2MyNjE2Nzc3OTRlNjI2ZTI4MSIsImlhdCI6MTcyMjg3Mjc3MH0.6S0aNpSZWpU4MDgFPwc9kmlhLGw2W37Ke4-_i4IlWoA"

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname" : "aayush",
#     "email" : "aayush@yahoo.com",
#     "password" : "Aayush.19"
# }


# GET http://localhost:3000/get-upload-url

# POST http://localhost:3000/create-blog
# Content-Type : application/json

# {
#     "blog-name" : "test blog"
# }

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email" : "yashfirake2002@gmail.com",
#     "password" : "Aayush.19"
# }

POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjBmM2MyNjE2Nzc3OTRlNjI2ZTI4MSIsImlhdCI6MTcyMjg3Mjc3MH0.6S0aNpSZWpU4MDgFPwc9kmlhLGw2W37Ke4-_i4IlWoA

# {
#     "title" : "test title"
# }
{
    "title": "test title",
    "banner" : "https://example.com/image-url",
    "des" : "this is a short des",
    "content" : {
        "blocks" : [1, 2]
    },
    "tags" : ["tag1", "tag2"]

}